
name: Build
on: [push]
jobs:
  main:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        run: pip install buildozer cython kivy
      - name: Build
        run: |
          [ -f buildozer.spec ] || buildozer init
          sed -i 's/package.name = myapp/package.name = smartcalc/' buildozer.spec
          sed -i 's/# android.accept_sdk_license = False/android.accept_sdk_license = True/' buildozer.spec
          buildozer android debug
      - name: List files
        run: find . -name "*.apk"
      - uses: actions/upload-artifact@v4
        with:
          name: Calculator-APK
          path: "**/*.apk" # Ищем во всех папках!
