
name: Build
on: [push]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install
        run: pip install buildozer cython kivy
      - name: Build with Licenses
        run: |
          buildozer init
          sed -i 's/# android.accept_sdk_license = False/android.accept_sdk_license = True/' buildozer.spec
          yes | buildozer android debug
      - uses: actions/upload-artifact@v4
        with:
          name: Winner-APK
          path: bin/*.apk
