
name: Build
on: [push]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install
        run: pip install buildozer cython kivy
      - name: Build APK
        run: |
          [ -f buildozer.spec ] || buildozer init
          sed -i 's/# android.accept_sdk_license = False/android.accept_sdk_license = True/' buildozer.spec
          buildozer android debug
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: MyFirstApp
          path: bin/*.apk
          if-no-files-found: error
