
name: Build
on: [push]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          pip install buildozer cython kivy
          sudo apt install -y libffi-dev gzip zip unzip
          [ -f buildozer.spec ] || buildozer init
          yes | buildozer android debug
      - uses: actions/upload-artifact@v2
        with:
          name: App
          path: bin/*.apk
